export const translations = {
  ko: {
    title: '말레이시아 AI 챗봇 어드민',
    systemOnline: 'System Online',
    admin: '관리자',
    dashboard: '대시보드',
    userManagement: '유저 관리',
    activeChats: '활성화된 대화',
    settings: '설정',
    activeChatCount: '개의 활성화된 채팅',
    selectConversation: '대화를 선택해주세요',
    selectConversationDesc: '왼쪽에서 대화를 선택하면 채팅 내용이 여기에 표시됩니다.',
    manualMode: 'Manual Mode',
    aiMode: 'AI Mode',
    userDetails: '사용자 정보',
    email: '이메일',
    phone: '핸드폰',
    region: '지역',
    carModel: '차종',
    carNumber: '차량번호',
    totalChats: '총 채팅 수',
    lastChat: '최근 채팅',
    quickActions: 'Quick Actions',
    exportChat: '채팅 내역 추출',
    addBlacklist: '블랙리스트 추가',
    chatHistory: 'Chat History',
    typeMessage: '메시지를 입력하세요...',
    darkMode: '다크모드',
    darkModeOn: '다크 테마 사용 중',
    darkModeOff: '라이트 테마 사용 중',
    language: '언어',
    totalUsers: '총 사용자',
    activeUsers: '활성 사용자',
    dashboardTotalChats: '총 채팅',
    chatsPerDay: '일별 채팅 수',
    usersByRegion: '지역별 사용자',
    usersByCarModel: '차종별 사용자',
    userInsights: '사용자 인사이트',
    quickControls: '빠른 제어',
    recentActivity: '최근 활동',
    newUser: '신규 사용자',
    returningUser: '재방문 사용자',
    sendAnnouncement: '공지 발송',
    toggleMaintenance: '점검 모드 전환',
    faqTop3: '자주 묻는 질문 TOP 3',
    userSatisfaction: '사용자 만족도',
    performanceMetrics: '성능 지표',
    responseTime: '응답 속도',
    satisfaction: '만족도',
    serviceUptime: '서비스 가동률'
  },
  en: {
    title: 'Malaysia AI Chatbot Admin',
    systemOnline: 'System Online',
    admin: 'Admin',
    dashboard: 'Dashboard',
    userManagement: 'User Management',
    activeChats: 'Active Chats',
    settings: 'Settings',
    activeChatCount: 'active chats',
    selectConversation: 'Select a conversation',
    selectConversationDesc: 'Choose a conversation from the left to view chat details here.',
    manualMode: 'Manual Mode',
    aiMode: 'AI Mode',
    userDetails: 'User Details',
    email: 'Email',
    phone: 'Phone',
    region: 'Region',
    carModel: 'Car Model',
    carNumber: 'Car Number',
    totalChats: 'Total Chats',
    lastChat: 'Last Chat',
    quickActions: 'Quick Actions',
    exportChat: 'Export Chat',
    addBlacklist: 'Add to Blacklist',
    chatHistory: 'Chat History',
    typeMessage: 'Type a message...',
    darkMode: 'Dark Mode',
    darkModeOn: 'Dark theme enabled',
    darkModeOff: 'Light theme enabled',
    language: 'Language',
    totalUsers: 'Total Users',
    activeUsers: 'Active Users',
    dashboardTotalChats: 'Total Chats',
    chatsPerDay: 'Chats per Day',
    usersByRegion: 'Users by Region',
    usersByCarModel: 'Users by Car Model',
    userInsights: 'User Insights',
    quickControls: 'Quick Controls',
    recentActivity: 'Recent Activity',
    newUser: 'New User',
    returningUser: 'Returning User',
    sendAnnouncement: 'Send Announcement',
    toggleMaintenance: 'Toggle Maintenance',
    faqTop3: 'FAQ TOP 3',
    userSatisfaction: 'User Satisfaction',
    performanceMetrics: 'Performance Metrics',
    responseTime: 'Response Time',
    satisfaction: 'Satisfaction',
    serviceUptime: 'Service Uptime'
  },
  ms: {
    title: 'Admin Chatbot AI Malaysia',
    systemOnline: 'Sistem Dalam Talian',
    admin: 'Pentadbir',
    dashboard: 'Papan Pemuka',
    userManagement: 'Pengurusan Pengguna',
    activeChats: 'Perbualan Aktif',
    settings: 'Tetapan',
    activeChatCount: 'perbualan aktif',
    selectConversation: 'Pilih perbualan',
    selectConversationDesc: 'Pilih perbualan dari sebelah kiri untuk melihat butiran chat di sini.',
    manualMode: 'Mod Manual',
    aiMode: 'Mod AI',
    userDetails: 'Butiran Pengguna',
    email: 'E-mel',
    phone: 'Telefon',
    region: 'Wilayah',
    carModel: 'Model Kereta',
    carNumber: 'Nombor Kereta',
    totalChats: 'Jumlah Chat',
    lastChat: 'Chat Terakhir',
    quickActions: 'Tindakan Pantas',
    exportChat: 'Eksport Chat',
    addBlacklist: 'Tambah ke Senarai Hitam',
    chatHistory: 'Sejarah Chat',
    typeMessage: 'Taip mesej...',
    darkMode: 'Mod Gelap',
    darkModeOn: 'Tema gelap diaktifkan',
    darkModeOff: 'Tema terang diaktifkan',
    language: 'Bahasa',
    totalUsers: 'Jumlah Pengguna',
    activeUsers: 'Pengguna Aktif',
    dashboardTotalChats: 'Jumlah Perbualan',
    chatsPerDay: 'Perbualan setiap Hari',
    usersByRegion: 'Pengguna mengikut Wilayah',
    usersByCarModel: 'Pengguna mengikut Model Kereta',
    userInsights: 'Wawasan Pengguna',
    quickControls: 'Kawalan Pantas',
    recentActivity: 'Aktiviti Terkini',
    newUser: 'Pengguna Baru',
    returningUser: 'Pengguna Kembali',
    sendAnnouncement: 'Hantar Pengumuman',
    toggleMaintenance: 'Togol Mod Penyelenggaraan',
    faqTop3: 'Soalan Lazim TOP 3',
    userSatisfaction: 'Kepuasan Pengguna',
    performanceMetrics: 'Metrik Prestasi',
    responseTime: 'Masa Respons',
    satisfaction: 'Kepuasan',
    serviceUptime: 'Masa Aktif Perkhidmatan'
  }
};

export const mockChats = [
  {
    id: 1,
    userName: 'Ahmad Rahman',
    userId: '#USER-234920-234',
    avatar: '/images/user-avatar.png',
    lastMessage: 'Saya ada masalah dengan kereta saya, boleh tolong?',
    timestamp: '2 min ago',
    isOnline: true,
    mode: 'ai',
    email: 'ahmad.rahman@email.com',
    phone: '+60123456789',
    region: 'Kuala Lumpur',
    carModel: 'Honda Civic',
    carNumber: 'ABC1234',
    totalChats: 23,
    lastChatDate: '2024-07-09'
  },
  {
    id: 2,
    userName: 'Siti Nurhaliza',
    userId: '#USER-345821-567',
    avatar: '/images/user-avatar1.png',
    lastMessage: 'Terima kasih atas bantuan anda.',
    timestamp: '5 min ago',
    isOnline: false,
    mode: 'manual',
    email: 'siti.nur@email.com',
    phone: '+60198765432',
    region: 'Penang',
    carModel: 'Toyota Vios',
    carNumber: 'DEF5678',
    totalChats: 15,
    lastChatDate: '2024-07-09'
  },
  {
    id: 3,
    userName: 'Raj Kumar',
    userId: '#USER-456732-890',
    avatar: '/images/user-avatar2.png',
    lastMessage: 'How do I check my car insurance policy?',
    timestamp: '10 min ago',
    isOnline: true,
    mode: 'ai',
    email: 'raj.kumar@email.com',
    phone: '+60167891234',
    region: 'Johor Bahru',
    carModel: 'Perodua Myvi',
    carNumber: 'GHI9012',
    totalChats: 8,
    lastChatDate: '2024-07-08'
  }
];

export const mockMessages = [
  { id: 1, sender: 'user', message: 'Saya ada masalah dengan kereta saya', timestamp: '10:30 AM', avatar: '/images/user-avatar.png' },
  { id: 2, sender: 'ai', message: 'Terima kasih telah menghubungi kami. Boleh ceritakan masalah apa yang anda hadapi?', timestamp: '10:31 AM' },
  { id: 3, sender: 'user', message: 'Kereta saya tidak boleh start pagi ini', timestamp: '10:32 AM', avatar: '/images/user-avatar.png' },
  { id: 4, sender: 'ai', message: 'Saya faham. Ada bunyi apa-apa ketika anda cuba start kereta?', timestamp: '10:33 AM' },
  { id: 5, sender: 'admin', message: 'Sila periksa bateri kereta anda.', timestamp: '10:35 AM', avatar: '/images/user-avatar4.png' }
];